services:
  - type: web
    name: lraiadvpro-educational-platform
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: FLASK_ENV
        value: production
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
